erDiagram

EVENTO{
    INT ID_EVENTO 
    STRING NOMBRE 
    STRING TIPO 
    STRING FECHA 
    INT PONENTE FK 


}

ASISTENTE{
INT ID_ASISTENTE PK 
STRING NOMBRE 
STRING CORREO 

}

PONENTE{
INT ID_PONENTE PK 
STRING NOMBRE 
STRING ESPECIADAD 

}

INSCRIPCION{
INT ID_EVENTO FK
INT ID_ASISTEENTE FK 
STRING FECHA DE INSCRIPCION 


}

EVENTO||--o{INSCRIPCION:"genera"
ASISTENTE||--o{PONENTE:"recibe"
PONENTE||--o{INSCRIPCION:"genera"